version: '3.5' # specify docker-compose version

# Define the services/containers to be run
services:
  insuranceui-service: # name of the first service
    container_name: insuranceui-container
    build: ./ # specify the directory of the Dockerfile
    volumes: # Volume binding
      - './:/usr/src/app'
    ports:
      - "4200:80" # specify port forewarding
